using System.Linq;
using Content.Client.UserInterface.Controls;
using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._DeepLagoon.WebUI;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class SeparatedChatGameScreen : InGameScreen
{
    private readonly IConfigurationManager _chatConfig = IoCManager.Resolve<IConfigurationManager>();
    private float _chatWidth;
    private bool _applyingChatWidth;

    public SeparatedChatGameScreen()
    {
        RobustXamlLoader.Load(this);

        var menuGrid = new AdaptiveGridContainer { HorizontalExpand = true };
        foreach (var button in TopBar.Children.ToArray())
        {
            button.Orphan();
            button.MinSize = new Vector2(42, 48);
            button.SetWidth = 48;
            menuGrid.AddChild(button);
        }
        TopBar.AddChild(menuGrid);
        Chat.ChatInput.UseCompactLayout();
        Chat.EnableTguiChat();
        ChatTabsPanel.Visible = false;
        _chatWidth = Math.Clamp(_chatConfig.GetCVar(WebUiCVars.ChatPanelWidth), 0.15f, 0.55f);
        ScreenContainer.OnSplitResized += () =>
        {
            if (_applyingChatWidth || ScreenContainer.Width <= 0) return;
            _chatWidth = Math.Clamp(1 - ScreenContainer.SplitFraction, 0.15f, 0.55f);
            ApplyChatWidth();
            ResizeActionContainer();
        };
        ScreenContainer.OnSplitResizeFinished += () => _chatConfig.SetCVar(WebUiCVars.ChatPanelWidth, _chatWidth);

        SetAnchorPreset(ScreenContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetGrowHorizontal(ViewportContainer, GrowDirection.Constrain);
        SetAnchorPreset(SeparatedChatPanel, LayoutPreset.Wide);
        SetGrowHorizontal(SeparatedChatPanel, GrowDirection.Constrain);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(TopLeftContainer, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.CenterRight, margin: 10);
        SetAnchorAndMarginPreset(Targeting, LayoutPreset.BottomRight, margin: 5);

        ViewportContainer.OnResized += ResizeActionContainer;
    }

    private void ResizeActionContainer()
    {
        float indent = 20;
        Actions.ActionsContainer.MaxGridWidth = Math.Max(1, ViewportContainer.Size.X - indent);
    }

    public override ChatBox ChatBox => GetWidget<ChatBox>()!;

    public override void SetChatSize(Vector2 size)
    {
        // Legacy ui.separated_chat_size describes a different layout. Width now has
        // its own archived setting, adjusted by the native split handle.
        ApplyChatWidth();
    }

    public void SetChatPanelWidth(float fraction)
    {
        _chatWidth = Math.Clamp(fraction, 0.15f, 0.55f);
        ApplyChatWidth();
    }

    private void ApplyChatWidth()
    {
        if (ScreenContainer.Width <= 0 || _applyingChatWidth) return;
        _applyingChatWidth = true;
        ScreenContainer.SplitFraction = 1 - Math.Clamp(_chatWidth, Math.Min(0.55f, 320f / ScreenContainer.Width), 0.55f);
        // Pane preferred sizes are intentionally independent of the split.
        // Force layout even when the measure result therefore stays unchanged.
        ScreenContainer.InvalidateArrange();
        InvalidateArrange();
        _applyingChatWidth = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (ScreenContainer.Width > 0 && Math.Abs(ScreenContainer.SplitFraction - (1 - Math.Clamp(_chatWidth, Math.Min(0.55f, 320f / ScreenContainer.Width), 0.55f))) > 0.001f)
            ApplyChatWidth();
    }
}
