using System.Linq;
using Content.Client.UserInterface.Controls;
using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class SeparatedChatGameScreen : InGameScreen
{
    public SeparatedChatGameScreen()
    {
        RobustXamlLoader.Load(this);

        var menuGrid = new AdaptiveGridContainer { HorizontalExpand = true };
        foreach (var button in TopBar.Children.ToArray())
        {
            button.Orphan();
            button.MinSize = new Vector2(42, 48);
            button.SetWidth = 48;
            menuGrid.AddChild(button);
        }
        TopBar.AddChild(menuGrid);
        Chat.ChatInput.UseCompactLayout();
        Chat.EnableTabs(ChatTabsPanel);
        Chat.SetSidePanels(SeparatedChatPanel, ButtonsPanel, ChatTabsPanel);

        SetAnchorPreset(ScreenContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorRight(ViewportContainer, 0.8f);
        SetGrowHorizontal(ViewportContainer, GrowDirection.Constrain);
        SetAnchorPreset(SeparatedChatPanel, LayoutPreset.Wide);
        SetAnchorLeft(SeparatedChatPanel, 0.8f);
        SetGrowHorizontal(SeparatedChatPanel, GrowDirection.Constrain);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(TopLeftContainer, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.CenterRight, margin: 10);
        SetAnchorAndMarginPreset(Targeting, LayoutPreset.BottomRight, margin: 5);

        ViewportContainer.OnResized += ResizeActionContainer;
    }

    private void ResizeActionContainer()
    {
        float indent = 20;
        Actions.ActionsContainer.MaxGridWidth = Math.Max(1, ViewportContainer.Size.X - indent);
    }

    public override ChatBox ChatBox => GetWidget<ChatBox>()!;

    public override void SetChatSize(Vector2 size)
    {
        // The separated panel always occupies 20% of the current screen width.
        // Ignore the draggable split saved by earlier versions.
    }
}
