using System.Linq;
using Content.Client._DeepLagoon.WebUI;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.UserInterface.Systems.Guidebook;
using Robust.Client.Console;
using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Resources;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private IEntityManager _entManager = default!;
        [Dependency] private IPrototypeManager _protomanager = default!;
        [Dependency] private IResourceCache _resourceCache = default!;
        [Dependency] private IConfigurationManager _cfg = default!;


        private readonly HumanoidProfileEditor _editor;
        public event Action? CloseRequested;
        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var panelTex = _resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = new Color(37, 37, 42)
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);

            BackgroundPanel.PanelOverride = back;

            _editor = profileEditor;
            CharEditor.AddChild(profileEditor);
            Header.Visible = CharactersSidebar.Visible = SidebarSeparator.Visible = false;
            profileEditor.SetupState = CreateTguiSetupState;
            profileEditor.SetupAction = HandleTguiSetupAction;
            _cfg.OnValueChanged(CCVars.SeeOwnNotes, p => AdminRemarksButton.Visible = p, true);
        }

        protected override void Resized()
        {
            base.Resized();
            Header.Visible = CharactersSidebar.Visible = SidebarSeparator.Visible = false;
        }

        private TguiData CreateTguiSetupState()
        {
            var preferences = _preferencesManager.Preferences;
            var requirements = IoCManager.Resolve<JobRequirementsManager>();
            return new TguiData().Number("selected", preferences?.SelectedCharacterIndex ?? -1)
                .Bool("canCreate", _preferencesManager.ServerDataLoaded && preferences != null && preferences.Characters.Count < (_preferencesManager.Settings?.MaxCharacterSlots ?? 0))
                .Bool("notes", _cfg.GetCVar(CCVars.SeeOwnNotes))
                .String("overallTime", requirements.FetchOverallPlaytime().ToString())
                .Array("playtimes", requirements.FetchPlaytimeByRoles().Select(time => new TguiData().String("name", Loc.GetString(time.Key)).String("time", time.Value.ToString())))
                .Array("characters", preferences?.Characters.Select(entry => new TguiData().Number("slot", entry.Key).String("name", entry.Value.Name)
                    .String("balance", entry.Value is HumanoidCharacterProfile profile ? profile.BankBalanceText : "")) ?? Enumerable.Empty<TguiData>());
        }

        private bool HandleTguiSetupAction(string action, TguiActionData args)
        {
            switch (action)
            {
                case "close": CloseRequested?.Invoke(); return true;
                case "rules": UserInterfaceManager.GetUIController<GuidebookUIController>().OpenWikiPage("Rules"); return true;
                case "notes":
                    if (!_cfg.GetCVar(CCVars.SeeOwnNotes)) return false;
                    IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand("adminremarks"); return true;
                case "create":
                    if (!_preferencesManager.ServerDataLoaded || _preferencesManager.Preferences == null || _preferencesManager.Preferences.Characters.Count >= _preferencesManager.Settings!.MaxCharacterSlots) return false;
                    _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random()); ReloadCharacterPickers(); return true;
                case "select": case "delete":
                    if (!args.TryInt("slot", out var slot) || _preferencesManager.Preferences?.Characters.ContainsKey(slot) != true) return false;
                    if (action == "select") SelectCharacter?.Invoke(slot);
                    else
                    {
                        if (slot == _preferencesManager.Preferences.SelectedCharacterIndex) return false;
                        DeleteCharacter?.Invoke(slot);
                    }
                    return true;
                default: return false;
            }
        }

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers() => _editor.RefreshTguiSetup();
    }
}
