using System.Numerics;
using Content.Client._DeepLagoon.WebUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterSetupGuiSavePanel : DefaultWindow
{
    public event Action? SaveRequested;
    public event Action? DiscardRequested;

    public CharacterSetupGuiSavePanel()
    {
        RobustXamlLoader.Load(this);

        CancelButton.OnPressed += _ =>
        {
            Close();
        };

        CloseButton.Visible = false;
        Contents.DisposeAllChildren();
        SetSize = new Vector2(430, 210);
        var panel = new TguiPanel();
        panel.SetState("CharacterSavePrompt", "{}");
        panel.OnAction += (action, _) =>
        {
            if (action == "save") SaveRequested?.Invoke();
            else if (action == "discard") DiscardRequested?.Invoke();
            else if (action == "cancel") Close();
        };
        Contents.AddChild(panel);
    }
}
