using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;

        private string _lastLobbyState = "";

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            Chat.ChatInput.UseCompactLayout();
            Chat.EnableTguiChat();
            LobbyActions.Orphan();
            TopLeft.AddChild(LobbyActions);
            ServerInfo.Orphan();
            TopLeft.AddChild(ServerInfo);
            HeaderContainer.Visible = LobbyInfoScroll.Visible = StartTime.Visible = false;

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
        }

        protected override void FrameUpdate(Robust.Shared.Timing.FrameEventArgs args)
        {
            base.FrameUpdate(args);
            HeaderContainer.Visible = LobbyInfoScroll.Visible = StartTime.Visible = Chat.WebChat == null;
            var state = new Content.Client._DeepLagoon.WebUI.TguiData().String("server", ServerName.Text)
                .String("time", StationTime.Text).String("status", StartTime.Text).ToString();
            if (Chat.WebChat?.IsReady == true && state != _lastLobbyState)
            {
                _lastLobbyState = state;
                Chat.WebChat.Send("deeplagoon/lobby-status", state);
            }
            if (Chat.WebChat?.IsReady != true) _lastLobbyState = "";
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                      DefaultState.Visible = true;
                      RightSide.Visible = true;
                      UserInterfaceManager.GetUIController<LobbyUIController>().OpenCharacterEditor();

                    break;
            }
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
