// Content-owned spawn window, based on the RobustToolbox implementation.
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DeepLagoon.Spawn;

[GenerateTypedNameReferences]
public sealed partial class TileSpawnWindow : DefaultWindow
{
    public TileSpawnWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Opened()
    {
        base.Opened();
        
        SearchBar.GrabKeyboardFocus();
    }
}
